// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: haven/haven.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Haven struct {
	Uid      uint64     `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name     string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Owner    string     `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Rake     uint64     `protobuf:"varint,4,opt,name=rake,proto3" json:"rake,omitempty"`
	Earnings types.Coin `protobuf:"bytes,5,opt,name=earnings,proto3" json:"earnings"`
}

func (m *Haven) Reset()         { *m = Haven{} }
func (m *Haven) String() string { return proto.CompactTextString(m) }
func (*Haven) ProtoMessage()    {}
func (*Haven) Descriptor() ([]byte, []int) {
	return fileDescriptor_a8def75b5794787f, []int{0}
}
func (m *Haven) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Haven) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Haven.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Haven) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Haven.Merge(m, src)
}
func (m *Haven) XXX_Size() int {
	return m.Size()
}
func (m *Haven) XXX_DiscardUnknown() {
	xxx_messageInfo_Haven.DiscardUnknown(m)
}

var xxx_messageInfo_Haven proto.InternalMessageInfo

func (m *Haven) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Haven) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Haven) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Haven) GetRake() uint64 {
	if m != nil {
		return m.Rake
	}
	return 0
}

func (m *Haven) GetEarnings() types.Coin {
	if m != nil {
		return m.Earnings
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*Haven)(nil), "haven.haven.Haven")
}

func init() { proto.RegisterFile("haven/haven.proto", fileDescriptor_a8def75b5794787f) }

var fileDescriptor_a8def75b5794787f = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x63, 0x9a, 0x20, 0x70, 0x17, 0xb0, 0x3a, 0x84, 0x0e, 0x26, 0x62, 0xca, 0x80, 0x6c,
	0x15, 0x46, 0xb6, 0x22, 0x21, 0xe6, 0x8c, 0x6c, 0x4e, 0xb0, 0x52, 0x0b, 0xe2, 0xab, 0xe2, 0xb4,
	0xd0, 0xb7, 0x60, 0xe0, 0xa1, 0x3a, 0x76, 0x64, 0x42, 0x28, 0x79, 0x11, 0xe4, 0x73, 0xd4, 0xe5,
	0xfc, 0xdd, 0xf9, 0xff, 0xad, 0xdf, 0x47, 0x2f, 0x57, 0x6a, 0xab, 0xad, 0xc4, 0x2a, 0xd6, 0x2d,
	0x74, 0xc0, 0xa6, 0xa1, 0xc1, 0x3a, 0x9f, 0xd5, 0x50, 0x03, 0xce, 0xa5, 0xa7, 0x20, 0x99, 0xf3,
	0x0a, 0x5c, 0x03, 0x4e, 0x96, 0xca, 0x69, 0xb9, 0x5d, 0x94, 0xba, 0x53, 0x0b, 0x59, 0x81, 0x19,
	0x9f, 0xb8, 0xf9, 0x26, 0x34, 0x79, 0xf6, 0x7e, 0x76, 0x41, 0x27, 0x1b, 0xf3, 0x9a, 0x92, 0x8c,
	0xe4, 0x71, 0xe1, 0x91, 0x31, 0x1a, 0x5b, 0xd5, 0xe8, 0xf4, 0x24, 0x23, 0xf9, 0x79, 0x81, 0xcc,
	0x66, 0x34, 0x81, 0x0f, 0xab, 0xdb, 0x74, 0x82, 0xc3, 0xd0, 0x78, 0x65, 0xab, 0xde, 0x74, 0x1a,
	0xa3, 0x19, 0x99, 0x3d, 0xd0, 0x33, 0xad, 0x5a, 0x6b, 0x6c, 0xed, 0xd2, 0x24, 0x23, 0xf9, 0xf4,
	0xee, 0x4a, 0x84, 0x30, 0xc2, 0x87, 0x11, 0x63, 0x18, 0xf1, 0x08, 0xc6, 0x2e, 0xe3, 0xfd, 0xef,
	0x75, 0x54, 0x1c, 0x0d, 0xcb, 0xa7, 0x7d, 0xcf, 0xc9, 0xa1, 0xe7, 0xe4, 0xaf, 0xe7, 0xe4, 0x6b,
	0xe0, 0xd1, 0x61, 0xe0, 0xd1, 0xcf, 0xc0, 0xa3, 0x97, 0xdb, 0xda, 0x74, 0xab, 0x4d, 0x29, 0x2a,
	0x68, 0x24, 0x58, 0x68, 0x76, 0xf8, 0x8f, 0x0a, 0xde, 0xc3, 0x66, 0xe4, 0xe7, 0x78, 0x76, 0xbb,
	0xb5, 0x76, 0xe5, 0x29, 0xde, 0xde, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x97, 0x43, 0x1a, 0x5c,
	0x3d, 0x01, 0x00, 0x00,
}

func (m *Haven) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Haven) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Haven) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Earnings.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintHaven(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.Rake != 0 {
		i = encodeVarintHaven(dAtA, i, uint64(m.Rake))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintHaven(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintHaven(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if m.Uid != 0 {
		i = encodeVarintHaven(dAtA, i, uint64(m.Uid))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintHaven(dAtA []byte, offset int, v uint64) int {
	offset -= sovHaven(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Haven) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Uid != 0 {
		n += 1 + sovHaven(uint64(m.Uid))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovHaven(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovHaven(uint64(l))
	}
	if m.Rake != 0 {
		n += 1 + sovHaven(uint64(m.Rake))
	}
	l = m.Earnings.Size()
	n += 1 + l + sovHaven(uint64(l))
	return n
}

func sovHaven(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozHaven(x uint64) (n int) {
	return sovHaven(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Haven) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHaven
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Haven: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Haven: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uid", wireType)
			}
			m.Uid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHaven
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Uid |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHaven
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHaven
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHaven
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHaven
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthHaven
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthHaven
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rake", wireType)
			}
			m.Rake = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHaven
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Rake |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Earnings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHaven
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthHaven
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthHaven
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Earnings.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHaven(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHaven
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipHaven(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowHaven
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHaven
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHaven
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthHaven
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupHaven
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthHaven
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthHaven        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHaven          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHaven = fmt.Errorf("proto: unexpected end of group")
)
