name: CI

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19
        id: go
      - name: Checkout
        uses: actions/checkout@v2
      - name: test suite
        run: |
          go install mvdan.cc/gofumpt@latest
          test -z "$(gofumpt -d -e -extra . | tee /dev/stderr)"
          go build ./...
          go test ./...
