on:
  push:
    tags:
      - "v*"

name: Automated release build

jobs:
  build:
    name: Build and upload release assets
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: true

      # build & upload havend

      - name: Build havend
        run: make build

      - name: Upload havend
        id: upload-havend-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: havend
          asset_name: havend
          asset_content_type: application/bin

      # build & upload havend arm64

      - name: Build havend arm64
        run: GOARCH=arm64 make build

      - name: Upload havend arm64
        id: upload-havend-release-asset-arm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: havend
          asset_name: havend-arm
          asset_content_type: application/bin
